const responseCodeConstant = {
	// -------------------- GENERAL VALIDATION (100–110) --------------------
	SUCCESS: 200,
	MISSING_HEADERS: 100,
	INVALID_DEVICE_TYPE: 101,
	INVALID_API_KEY: 102,
	MISSING_OR_MALFORMED_AUTH_TOKEN: 103,
	INVALID_TOKEN: 104,
	VALIDATION_ERROR: 105,
	INTERNAL_SERVER_ERROR: 106,
	INVALID_JSON_FORMAT: 107,
	ACCESS_DENIED: 108,

	// -------------------- AUTH / LOGIN / SECURITY --------------------
	INVALID_LOGIN_CREDENTIALS: 120,
	JWT_TOKEN_EXPIRED: 121,
	PASSWORD_MISMATCH: 122,
	TEMP_PASSWORD_INVALID: 123,
	OTP_LIMIT_EXCEEDED: 124,
	OTP_INVALID: 125,

	// -------------------- USER / ACCOUNT --------------------
	USER_NOT_FOUND: 140,
	ACCOUNT_NOT_FOUND: 141,
	ACCOUNT_INACTIVE: 142,
	ACCOUNT_BLOCKED: 143,
	ACCOUNT_DELETED: 144,

	// -------------------- UNIQUENESS / CONFLICT --------------------
	EMAIL_ALREADY_EXISTS: 160,
	PHONE_ALREADY_EXISTS: 161,
	USERNAME_ALREADY_EXISTS: 162,

	// -------------------- EMAIL / MESSAGING --------------------
	EMAIL_SEND_FAILED: 180,
	MESSAGE_SEND_FAILED: 181,
	CODE_MISMATCH: 182,
	CODE_ALREADY_USED: 183,

	// -------------------- FILE / MEDIA --------------------
	FILE_SIZE_LIMIT: 211,
	INVALID_FILE_EXTENSION: 212,
	PROFILE_IMAGE_REQUIRED: 213,


	UNSUPPORTED_MEDIA_TYPE: 415
}

export default responseCodeConstant;